language: python
sudo: false
python:
    - "3.4"

env:
  global:
      # encrypted AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to push to S3
      - secure: "cK5nhaYCN8lo36k+BOCWdf1AJ35Pse5etnke407+C4wFPxKOfaTaE8fVoTfQevD4sWk1gYg9hGz/1H1hEfDPrp+HdwKuwJ/jP7vAaXMuR2Czz+Sgw67XYblsv11DrbvPpanXuFnRsKf88l3Z9GzSeN9LJ/mjasfgBKRI/FwBa8c="
      - secure: "hAYRMpDDm6oMZbWHcLbucAcb2KdoIrfZMjoT0rkpjA8VWDwV5K07tcacziVeiR1MgtmHARx0ZI9vrO5Qu+z8/Gui0U564RWoTq9UAlIBVN6Ee83AdoVGR6ZyxoqAByviYZumvbW6rG6B1u9qyEJoZ27tHPSrwm71YNpqkzVE+3s="

install: "pip install -r requirements.txt"

script: "make publish"

deploy:
  provider: script
  access_key_id:
    secure: "erx0Hz/S+MwsWPHkVDNDeqCwwlHdR8/UuaSQ4xc5FwUgCb5AGGpp6vy4e7bcz3ikfvma0MSU7e4nliE+f8sb2jiNEs1mbh/7Oiw078lXDr4coGFaGraK5B4RIZegDqJhiBH8oI7irAj1Qsc9R5d7UxQdQzBzeGskL/GvU7jhWvE="
  aws_secret_access_key:
    secure: "kB/pDnhKWoFppSk2L9cYGPCENAoDxlFD59RQdhUDD2LGyeVDX4B/28ZWsVLDqKjhFk0QoQGVWZHbykN97uQqcipwgi748WrSoVC1N0a3E7XG51LpkmdgauzS1+PIKXaYEuSv6qj1fYheuc2GJLa13Tnz6fPn+ERt/kTtz4Hi10o="
  script: tools/deploy.sh
  on:
      branch: master


